### ISSUE TITLE
Old RC versions

### ISSUE THREAD

**Issue by AntoineD** [conda-forge/openturns-feedstock#178]
### Comment:

Hello,

sometimes the conda dependency resolver pulls openturn 1.20rc1 into an environment, causing troubles.
Would it be possible to remove the old RC versions?

**Comment by jschueller** [comment]
thats not surprising, dependencies of gemseo are probably too strict to find something else:
```
docstring-inheritance >=1.0.0,<=1.1.1
    - python-fastjsonschema >=2.14.5,<=2.16.3
    - genson ==1.2.2
    - h5py >=3.0.0,<=3.8.0
    - jinja2 >=3.0.0,<=3.1.2
    - matplotlib-base >=3.3.0,<=3.7.1
    - networkx >=2.2,<=3.1
    - numpy >=1.21,<=1.24.3
    - packaging <=23.1
    - pandas >=1.1.0,<=2.0.0
    - pyxdsm >=2.1.0,<=2.2.2
    - pydantic ==1.10.8
    - requests
    - scipy >=1.4,<=1.10.1
    - strenum >=0.4.9,<=0.4.10
    - tqdm >=4.41,<=4.65.0
    - typing-extensions >=4,<5
    - xdsmjs >=1.0.0,<=2.0.0
    - python-xxhash >=3.0.0,<=3.2.0
```

**Comment by AntoineD** [comment]
I do not understand, what is too strict?

We've never had installed RC versions from other packages when creating anaconda envs.

Surprisingly, the behavior is different when creating an env directly with mamba:
```console
❯ mamba create -p foo gemseo
...
+ openturns                       1.21rc1  py310h9820007_1          conda-forge/linux-64     Cached
...
❯ conda create -p bar gemseo
...
openturns          conda-forge/linux-64::openturns-1.20rc1-py310h2455298_2
...
```

But installing explicitly the stable version is allowed by the dependency resolver
```console
❯ <install path>/bin/conda install openturns==1.20
...
❯ <install path>/bin/conda list
...
openturns                 1.20            py310h2455298_0    conda-forge
...
```

**Comment by AntoineD** [comment]
Is there a reason to keep the RC versions when the final version has been released?

**Comment by jschueller** [comment]
do you think that's why the solver fails ?

**Comment by AntoineD** [comment]
I see no other reason.

**Comment by jschueller** [comment]
does it still happen with 1.21 ?
we also solved a problem with dlib resolution today

**Comment by jschueller** [comment]
it might be due to the dlib bug, hopefully this is fixed now, feel free to reopen if not

**Comment by AntoineD** [comment]
We are still having troubles with RC versions because the version `1.21rc1` matches the constraint `openturns >=1.16,<1.21`.

We get this kind of error:
```shell
py38/lib/python3.8/site-packages/openturns/__init__.py:49: in <module>
    from .common import *
py38/lib/python3.8/site-packages/openturns/common.py:12: in <module>
    from . import _common
E   ImportError: libdlib.so.19.24.0: cannot open shared object file: No such file or directory
```

Could you please remove the RC packages when final releases are available?

**Comment by AntoineD** [comment]
Hello @jschueller, should I create a new issue since this one is closed?

**Comment by jschueller** [comment]
maybe you can try pinning dlib-cpp to 19.24 instead of 19.24.2

**Comment by AntoineD** [comment]
Hello @jschueller,
eventhough we support openturns 1.21, the conda dependency resolver may pick openturns 1.20.rc1 which leads to the libdlib issue, would it be possible to mark this 1.20.rc1 as broken too please?

**Comment by jschueller** [comment]
see https://github.com/conda-forge/admin-requests/pull/830 to open a similar PR
