### ISSUE TITLE
Release names with RC causing problems

### ISSUE THREAD

**Issue by tupui** [conda-forge/openturns-feedstock#71]
When specifying in requirements `openturns >= 1.10`, it installs `1.12rc1` instead of `1.12`. Appart from the fact that this is not the latest version which is installed, this causes conflicts with `pip` which then will want to install `1.12`. The end result is a non working installation of openturns:

    >>> import openturns
    Fatal Python error: PyThreadState_Get: no current thread

    Abort trap: 6

So it forces to pin a particular version to avoid this behaviour.

A simple fix is to remove the `1.12rc1`, and in the futur, change the naming convention not to reproduce the problem.

**Comment by jschueller** [comment]
that's not the behavior i see here (Linux):
```conda install -y "openturns>=1.10"``` pulls 1.12, and in conda-build as well

**Comment by jschueller** [comment]
I just tried to build batman, it also pulls the 1.12, so i dont see what's wrong

**Comment by tupui** [comment]
OK I went down the problem. This is coming from the fact that `hmat-oss` was ok to use with 1.12rc1 and is now in conflict with 1.12. Thus, this dependency was present in a yml environment file and was forcing the pull to the latest compatible version with `hmat-oss` which is 1.12rc1. So not sure you have anything to do here, I guess you can close the issue. Thanks for the support Julien!

**Comment by jschueller** [comment]
Then the problem is related to the compiler migration, as hmat-oss was not migrated yet.
But you shouldnt need to list hmat-oss anyways, as its only used used by openturns.

**Comment by tupui** [comment]
OK I see. I was using an export of an environment with `conda env export > env.yml`. Hence the presence of `hmat-oss`.

**Comment by jschueller** [comment]
I pushed hmat-oss updates anyways, so shouldnt see this problem anymore.

**Comment by tupui** [comment]
Ok good to know, thank you 👍
